# ===== DATABASE =====
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/rgba?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root123}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.hibernate.ddl-auto=update

# ===== JWT =====
bezkoder.app.jwtSecret=${JWT_SECRET:======================BezKoder=Spring===========================}
bezkoder.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}

# ===== CORS =====
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

# ===== SERVER =====
server.port=${PORT:8080}
